mingw: disable t9020
POSIX-to-Windows path mangling would make it fail. Symptoms:

	++ init_git
	++ rm -fr .git
	++ git init
	Initialized empty Git repository in [...]
	++ git remote add svnsim testsvn::sim:///usr/src/git/wip5/t/t9154/svn.dump
	++ git remote add svnfile testsvn::file:///usr/src/git/wip5/t/t9154/svn.dump
	++ git fetch svnsim
	progress Imported commit 1.
	fatal: Write to frontend failed: Bad file descriptor
	fast-import: dumping crash report to .git/fast_import_crash_23356
	fatal: error while running fast-import
	fatal: unexpected end of fast-import feedback
	error: last command exited with $?=128
	not ok 1 - simple fetch

Since the remote-svn project seems to be dormant at the moment (and not
complete enough to be used, which is a pity), let's just skip this test
on Windows.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>